### ISSUE TITLE
[FEAT] api 추가 구현

### ISSUE THREAD

**Issue by seaniiio** [likelion-inha-hackathon-2/Meong-Signal-BE#57]
## 🎯 목적
추가 구현 필요한 api

## ✅ 완료할 일
- 채팅방 생성 및 입장에 필요한 API
  - [x] dog_id 바탕으로 견주 정보 GET
  - [x] GET /users/me user_id만 (닉네임과 프사는 이미 존재함) + email 도 return하게
- [x] POST /walks/new 수정
   - [x] meong을 필요로 하지 않게 수정
   - [x] 산책한 이동 경로 사진을 img로 받을 수 있게 이미지 필드 추가?
- [x] 산책 정보 조회 시, 경로 사진도 받아오도록 수정
- [x] 챌린지 API 
   - [x] 이번주(월요일 0시부터 시작)에 산책한 거리 수, 강아지 수 return하는 api
- [x] 산책 기록 저장 시, 챌린지 조건 달성하면 멍 추가로 증가하도록 수정
- [ ] 추천 산책로 api에 코스 설명 추가
  - 어떤 산책로인지 설명도 있으면 좋을 것 같아요.
 - [x] 내가 보유한 상품 조회(혹은 구매 여부를 업적 달성처럼 0과 1로 설정)
구매를 했을 때 실제로 상품이 배송되는게 아니니까 내가 보유한 아이템 목록 같은 페이지도 필요하다고 생각해요! 
- [x] 리뷰를 위한 산책 정보 조회 시 견주가 아니라 유저 정보로 수정
- [x] 리뷰 작성할 때 멍 입력받아서 차감하게 수정 + 상대방은 멍 들어오게

**Comment by abyss-s** [comment]
화,,이팅😅

**Comment by seaniiio** [comment]
왐마... 💦

**Comment by abyss-s** [comment]
이거 근데 리뷰 작성할때는 산책 id가 필요한데, 
현재 내 정보 페이지에서는 산책 목록을 강아지 별로 조회할 수 있게 만들어서
특정 강아지 id를 넣었을때 해당하는 산책id들이 나오게 하는게 필요할거같아요
![2024-07-26 19 33 57](https://github.com/user-attachments/assets/e169f15d-534a-47e6-906a-8c7fb2b61381)

**Comment by seaniiio** [comment]
명세서의 "특정 강아지 정보 + 산책 기록 조회 api"에서 walk부분에 id만 추가하면 될까요?
